-- NTS Logo Studio Web V3.7
-- Community / Direct Messages / Feedback / Maintenance / Membership history
-- Run AFTER 001 -> 002 -> 003 -> 004.

begin;

-- ---------------------------------------------------------------------------
-- 1) Maintenance controls
-- ---------------------------------------------------------------------------
alter table public.site_settings
  add column if not exists maintenance_enabled boolean not null default false,
  add column if not exists maintenance_title text not null default 'Hệ thống đang bảo trì',
  add column if not exists maintenance_message text not null default 'NTS Logo Studio đang được nâng cấp. Vui lòng quay lại sau.',
  add column if not exists maintenance_updated_by uuid references auth.users(id) on delete set null;

-- ---------------------------------------------------------------------------
-- 2) Friend graph
-- ---------------------------------------------------------------------------
create table if not exists public.friendships (
  id uuid primary key default gen_random_uuid(),
  requester_id uuid not null references auth.users(id) on delete cascade,
  addressee_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined','blocked')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint friendships_not_self check (requester_id <> addressee_id)
);

create unique index if not exists friendships_unique_pair_idx
on public.friendships (least(requester_id, addressee_id), greatest(requester_id, addressee_id));
create index if not exists friendships_requester_idx on public.friendships(requester_id, status, updated_at desc);
create index if not exists friendships_addressee_idx on public.friendships(addressee_id, status, updated_at desc);

-- ---------------------------------------------------------------------------
-- 3) Direct messages
-- ---------------------------------------------------------------------------
create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  recipient_id uuid not null references auth.users(id) on delete cascade,
  body text not null,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  edited_at timestamptz,
  deleted_at timestamptz,
  constraint direct_messages_not_self check (sender_id <> recipient_id),
  constraint direct_messages_body_len check (char_length(btrim(body)) between 1 and 2000)
);
create index if not exists direct_messages_sender_recipient_idx on public.direct_messages(sender_id, recipient_id, created_at desc);
create index if not exists direct_messages_recipient_unread_idx on public.direct_messages(recipient_id, read_at, created_at desc);

-- ---------------------------------------------------------------------------
-- 4) User feedback / comments
-- ---------------------------------------------------------------------------
create table if not exists public.user_feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  feedback_type text not null default 'comment' check (feedback_type in ('comment','suggestion','bug','other')),
  rating smallint check (rating is null or rating between 1 and 5),
  content text not null,
  status text not null default 'new' check (status in ('new','reviewing','planned','resolved','rejected','archived')),
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint user_feedback_content_len check (char_length(btrim(content)) between 2 and 3000),
  constraint user_feedback_admin_note_len check (admin_note is null or char_length(admin_note) <= 2000)
);
create index if not exists user_feedback_user_idx on public.user_feedback(user_id, created_at desc);
create index if not exists user_feedback_status_idx on public.user_feedback(status, created_at desc) where deleted_at is null;

-- ---------------------------------------------------------------------------
-- 5) Membership history (soft-archiveable audit view)
-- ---------------------------------------------------------------------------
create table if not exists public.membership_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null default 'updated',
  old_role text,
  new_role text,
  old_plan text,
  new_plan text,
  old_status text,
  new_status text,
  old_vip_until timestamptz,
  new_vip_until timestamptz,
  admin_note text,
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists membership_history_user_idx on public.membership_history(user_id, created_at desc);
create index if not exists membership_history_created_idx on public.membership_history(created_at desc);

-- ---------------------------------------------------------------------------
-- 6) updated_at helpers
-- ---------------------------------------------------------------------------
drop trigger if exists friendships_set_updated_at on public.friendships;
create trigger friendships_set_updated_at before update on public.friendships
for each row execute function public.set_updated_at();

drop trigger if exists user_feedback_set_updated_at on public.user_feedback;
create trigger user_feedback_set_updated_at before update on public.user_feedback
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- 7) Membership audit trigger
-- ---------------------------------------------------------------------------
create or replace function public.log_membership_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.membership_history(
      user_id, actor_id, action,
      new_role, new_plan, new_status, new_vip_until
    ) values (
      new.user_id, auth.uid(), 'created',
      new.role, new.plan, new.status, new.vip_until
    );
    return new;
  end if;

  if old.role is distinct from new.role
     or old.plan is distinct from new.plan
     or old.status is distinct from new.status
     or old.vip_until is distinct from new.vip_until
     or old.free_limit is distinct from new.free_limit then
    insert into public.membership_history(
      user_id, actor_id, action,
      old_role, new_role, old_plan, new_plan, old_status, new_status,
      old_vip_until, new_vip_until
    ) values (
      new.user_id, auth.uid(), 'updated',
      old.role, new.role, old.plan, new.plan, old.status, new.status,
      old.vip_until, new.vip_until
    );
  end if;
  return new;
end;
$$;

drop trigger if exists memberships_history_trigger on public.memberships;
create trigger memberships_history_trigger
after insert or update on public.memberships
for each row execute function public.log_membership_change();

-- ---------------------------------------------------------------------------
-- 8) RLS
-- ---------------------------------------------------------------------------
alter table public.friendships enable row level security;
alter table public.direct_messages enable row level security;
alter table public.user_feedback enable row level security;
alter table public.membership_history enable row level security;

-- friendships: only participants, admin may inspect status metadata.
drop policy if exists friendships_select_participants on public.friendships;
create policy friendships_select_participants on public.friendships
for select to authenticated
using (requester_id = auth.uid() or addressee_id = auth.uid() or public.is_admin());

-- Do not allow arbitrary direct browser mutation: use RPCs below.
revoke insert, update, delete on public.friendships from authenticated;
grant select on public.friendships to authenticated;

-- direct messages: only sender/recipient can read. Admin does NOT get private message content.
drop policy if exists direct_messages_select_participants on public.direct_messages;
create policy direct_messages_select_participants on public.direct_messages
for select to authenticated
using (sender_id = auth.uid() or recipient_id = auth.uid());
revoke insert, update, delete on public.direct_messages from authenticated;
grant select on public.direct_messages to authenticated;

-- feedback: user can create/read own, admin can read/manage all.
drop policy if exists feedback_select_own_or_admin on public.user_feedback;
create policy feedback_select_own_or_admin on public.user_feedback
for select to authenticated
using ((user_id = auth.uid() and deleted_at is null) or public.is_admin());

drop policy if exists feedback_insert_own on public.user_feedback;
create policy feedback_insert_own on public.user_feedback
for insert to authenticated
with check (user_id = auth.uid() and deleted_at is null and status = 'new');

drop policy if exists feedback_admin_update on public.user_feedback;
create policy feedback_admin_update on public.user_feedback
for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists feedback_admin_delete on public.user_feedback;
create policy feedback_admin_delete on public.user_feedback
for delete to authenticated
using (public.is_admin());

grant select, insert on public.user_feedback to authenticated;
grant update, delete on public.user_feedback to authenticated;

-- membership history: users may read own; admins read/manage notes/archive.
drop policy if exists membership_history_select_own_or_admin on public.membership_history;
create policy membership_history_select_own_or_admin on public.membership_history
for select to authenticated
using ((user_id = auth.uid() and deleted_at is null) or public.is_admin());

drop policy if exists membership_history_admin_update on public.membership_history;
create policy membership_history_admin_update on public.membership_history
for update to authenticated
using (public.is_admin()) with check (public.is_admin());

drop policy if exists membership_history_admin_delete on public.membership_history;
create policy membership_history_admin_delete on public.membership_history
for delete to authenticated using (public.is_admin());

grant select, update, delete on public.membership_history to authenticated;

-- ---------------------------------------------------------------------------
-- 9) Safe member directory RPC
--    Does not expose email. Shows role / VIP badge as requested.
-- ---------------------------------------------------------------------------
create or replace function public.list_member_directory(p_search text default '', p_limit integer default 40)
returns table (
  user_id uuid,
  display_name text,
  avatar_url text,
  role text,
  plan text,
  is_vip boolean,
  friendship_id uuid,
  friendship_status text,
  friendship_direction text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id as user_id,
    coalesce(nullif(p.display_name,''), 'Hội viên') as display_name,
    p.avatar_url,
    coalesce(m.role,'member') as role,
    coalesce(m.plan,'free') as plan,
    (coalesce(m.role,'member') = 'admin' or (m.plan = 'vip' and m.status = 'active' and (m.vip_until is null or m.vip_until > now()))) as is_vip,
    f.id as friendship_id,
    f.status as friendship_status,
    case
      when f.requester_id = auth.uid() then 'outgoing'
      when f.addressee_id = auth.uid() then 'incoming'
      else null
    end as friendship_direction
  from public.profiles p
  left join public.memberships m on m.user_id = p.id
  left join public.friendships f
    on ((f.requester_id = auth.uid() and f.addressee_id = p.id)
        or (f.addressee_id = auth.uid() and f.requester_id = p.id))
  where auth.uid() is not null
    and p.id <> auth.uid()
    and coalesce(m.status,'active') <> 'suspended'
    and (
      coalesce(btrim(p_search),'') = ''
      or p.display_name ilike '%' || replace(replace(btrim(p_search),'%','\%'),'_','\_') || '%' escape '\'
    )
  order by
    case when f.status = 'accepted' then 0 when f.status = 'pending' then 1 else 2 end,
    case when m.role = 'admin' then 0 when m.plan = 'vip' then 1 else 2 end,
    lower(coalesce(p.display_name,''))
  limit greatest(1, least(coalesce(p_limit,40), 100));
$$;
revoke all on function public.list_member_directory(text, integer) from public;
grant execute on function public.list_member_directory(text, integer) to authenticated;

-- ---------------------------------------------------------------------------
-- 10) Friendship RPCs
-- ---------------------------------------------------------------------------
create or replace function public.send_friend_request(p_target uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_existing public.friendships%rowtype;
begin
  if auth.uid() is null then raise exception 'NOT_AUTHENTICATED'; end if;
  if p_target is null or p_target = auth.uid() then raise exception 'INVALID_TARGET'; end if;

  select * into v_existing
  from public.friendships
  where (requester_id = auth.uid() and addressee_id = p_target)
     or (requester_id = p_target and addressee_id = auth.uid())
  limit 1;

  if found then
    if v_existing.status = 'blocked' then raise exception 'FRIENDSHIP_BLOCKED'; end if;
    if v_existing.status in ('pending','accepted') then return v_existing.id; end if;
    update public.friendships
      set requester_id = auth.uid(), addressee_id = p_target, status = 'pending', responded_at = null
      where id = v_existing.id
      returning id into v_id;
    return v_id;
  end if;

  insert into public.friendships(requester_id, addressee_id, status)
  values (auth.uid(), p_target, 'pending') returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public.send_friend_request(uuid) from public;
grant execute on function public.send_friend_request(uuid) to authenticated;

create or replace function public.respond_friend_request(p_friendship uuid, p_action text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'NOT_AUTHENTICATED'; end if;
  if p_action not in ('accept','decline') then raise exception 'INVALID_ACTION'; end if;
  update public.friendships
  set status = case when p_action = 'accept' then 'accepted' else 'declined' end,
      responded_at = now()
  where id = p_friendship
    and addressee_id = auth.uid()
    and status = 'pending';
  if not found then raise exception 'REQUEST_NOT_FOUND'; end if;
end;
$$;
revoke all on function public.respond_friend_request(uuid, text) from public;
grant execute on function public.respond_friend_request(uuid, text) to authenticated;

create or replace function public.remove_friendship(p_friendship uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'NOT_AUTHENTICATED'; end if;
  delete from public.friendships
  where id = p_friendship
    and (requester_id = auth.uid() or addressee_id = auth.uid());
end;
$$;
revoke all on function public.remove_friendship(uuid) from public;
grant execute on function public.remove_friendship(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- 11) Messaging RPCs
-- ---------------------------------------------------------------------------
create or replace function public.send_direct_message(p_recipient uuid, p_body text)
returns public.direct_messages
language plpgsql
security definer
set search_path = public
as $$
declare
  v_body text := btrim(coalesce(p_body,''));
  v_row public.direct_messages;
  v_count integer;
begin
  if auth.uid() is null then raise exception 'NOT_AUTHENTICATED'; end if;
  if p_recipient is null or p_recipient = auth.uid() then raise exception 'INVALID_RECIPIENT'; end if;
  if char_length(v_body) < 1 or char_length(v_body) > 2000 then raise exception 'INVALID_MESSAGE_LENGTH'; end if;

  if not exists (
    select 1 from public.friendships f
    where f.status = 'accepted'
      and ((f.requester_id = auth.uid() and f.addressee_id = p_recipient)
        or (f.addressee_id = auth.uid() and f.requester_id = p_recipient))
  ) then raise exception 'NOT_FRIENDS'; end if;

  select count(*) into v_count
  from public.direct_messages
  where sender_id = auth.uid() and created_at > now() - interval '10 seconds';
  if v_count >= 8 then raise exception 'MESSAGE_RATE_LIMIT'; end if;

  insert into public.direct_messages(sender_id, recipient_id, body)
  values (auth.uid(), p_recipient, v_body)
  returning * into v_row;
  return v_row;
end;
$$;
revoke all on function public.send_direct_message(uuid, text) from public;
grant execute on function public.send_direct_message(uuid, text) to authenticated;

create or replace function public.mark_messages_read(p_peer uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare v_count integer;
begin
  if auth.uid() is null then raise exception 'NOT_AUTHENTICATED'; end if;
  update public.direct_messages
  set read_at = now()
  where recipient_id = auth.uid()
    and sender_id = p_peer
    and read_at is null
    and deleted_at is null;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
revoke all on function public.mark_messages_read(uuid) from public;
grant execute on function public.mark_messages_read(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- 12) Admin community stats
-- ---------------------------------------------------------------------------
create or replace function public.admin_community_stats()
returns table (
  friendships_total bigint,
  messages_total bigint,
  feedback_new bigint,
  feedback_total bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    (select count(*) from public.friendships where status='accepted'),
    (select count(*) from public.direct_messages where deleted_at is null),
    (select count(*) from public.user_feedback where status='new' and deleted_at is null),
    (select count(*) from public.user_feedback where deleted_at is null)
  where public.is_admin();
$$;
revoke all on function public.admin_community_stats() from public;
grant execute on function public.admin_community_stats() to authenticated;

-- ---------------------------------------------------------------------------
-- 13) Realtime publication - low-overhead tables only
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='direct_messages') then
    alter publication supabase_realtime add table public.direct_messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='friendships') then
    alter publication supabase_realtime add table public.friendships;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='site_settings') then
    alter publication supabase_realtime add table public.site_settings;
  end if;
end $$;

commit;
