(() => {
  "use strict";
  const $=id=>document.getElementById(id);const NTS=window.NTS=window.NTS||{};
  const state={user:null,account:null,settings:null,channel:null,saving:false,refreshing:null};
  const client=()=>NTS.supabase;const toast=(t,m,k="info",d)=>NTS.showToast?.(t,m,k,d);
  const isAdmin=()=>state.account?.role==="admin"&&state.account?.status==="active";

  function render(){const s=state.settings||{};if($("maintenanceEnabled"))$("maintenanceEnabled").checked=Boolean(s.maintenance_enabled);if($("maintenanceTitle"))$("maintenanceTitle").value=s.maintenance_title||"Hệ thống đang bảo trì";if($("maintenanceMessage"))$("maintenanceMessage").value=s.maintenance_message||"NTS Logo Studio đang được nâng cấp. Vui lòng quay lại sau.";if($("maintenanceStateLabel")){const on=Boolean(s.maintenance_enabled);$("maintenanceStateLabel").textContent=on?"ĐANG BẢO TRÌ":"Đang tắt";$("maintenanceStateLabel").dataset.kind=on?"danger":"ok";}
    const shouldBlock=Boolean(state.user&&state.account&&s.maintenance_enabled&&!isAdmin());$("maintenanceOverlay")?.classList.toggle("hidden",!shouldBlock);if($("maintenanceOverlayTitle"))$("maintenanceOverlayTitle").textContent=s.maintenance_title||"Hệ thống đang bảo trì";if($("maintenanceOverlayMessage"))$("maintenanceOverlayMessage").textContent=s.maintenance_message||"Vui lòng quay lại sau.";document.body.classList.toggle("maintenance-locked",shouldBlock);
  }
  async function refresh(){if(!client())return null;if(state.refreshing)return state.refreshing;state.refreshing=(async()=>{try{const req=client().from("site_settings").select("maintenance_enabled,maintenance_title,maintenance_message,maintenance_updated_by,updated_at").eq("id",true).single();const result=NTS.health?.withTimeout?await NTS.health.withTimeout(req,8000,"maintenance"):await req;if(result?.error)throw result.error;state.settings=result?.data||{};render();return state.settings;}catch(error){console.warn("maintenance refresh",error);return state.settings;}finally{state.refreshing=null;}})();return state.refreshing;}
  function subscribe(){if(!client()||state.channel)return;state.channel=client().channel("nts-site-settings-maintenance").on("postgres_changes",{event:"UPDATE",schema:"public",table:"site_settings",filter:"id=eq.true"},payload=>{state.settings={...(state.settings||{}),...(payload.new||{})};render();if(state.user&&!isAdmin()&&payload.new?.maintenance_enabled)toast("Website đang bảo trì",payload.new?.maintenance_message||"Vui lòng quay lại sau.","warning",6500);}).subscribe();}
  async function save(){if(!isAdmin()||state.saving||!client())return;state.saving=true;const btn=$("saveMaintenanceButton");if(btn){btn.disabled=true;btn.textContent="Đang lưu...";}try{const payload={maintenance_enabled:Boolean($("maintenanceEnabled")?.checked),maintenance_title:$("maintenanceTitle")?.value.trim()||"Hệ thống đang bảo trì",maintenance_message:$("maintenanceMessage")?.value.trim()||"NTS Logo Studio đang được nâng cấp. Vui lòng quay lại sau.",maintenance_updated_by:state.user?.id||null};const{data,error}=await client().from("site_settings").update(payload).eq("id",true).select("maintenance_enabled,maintenance_title,maintenance_message,maintenance_updated_by,updated_at").single();if(error)throw error;state.settings=data;render();toast(payload.maintenance_enabled?"Đã bật bảo trì":"Đã tắt bảo trì",payload.maintenance_enabled?"Hội viên đang đăng nhập sẽ bị khóa khỏi ứng dụng khi trạng thái Realtime cập nhật.":"Website đã mở lại cho hội viên.",payload.maintenance_enabled?"warning":"success",6000);}catch(error){console.error(error);toast("Không lưu được bảo trì",error.message||String(error),"error");}finally{state.saving=false;if(btn){btn.disabled=false;btn.textContent="Lưu trạng thái bảo trì";}}}
  $("saveMaintenanceButton")?.addEventListener("click",save);$("maintenanceLogoutButton")?.addEventListener("click",()=>client()?.auth.signOut());
  window.addEventListener("nts:auth-user",e=>{state.user=e.detail?.user||null;if(state.user){refresh();subscribe();}else{$("maintenanceOverlay")?.classList.add("hidden");document.body.classList.remove("maintenance-locked");}});
  window.addEventListener("nts:membership-updated",e=>{state.account=e.detail?.account||null;render();});
  if(NTS.currentUser){state.user=NTS.currentUser;refresh();subscribe();}
  NTS.maintenance={state,refresh,save};
})();
